### ISSUE TITLE
lintr in CI

### ISSUE THREAD

**Issue by ErdaradunGaztea** [ttscience/unbiased#3]
Kod powinien obowiązkowo przechodzić lint. Typowe wywołanie to `lintr::lint("ścieżka/do/pliku.R")` albo `lintr::lint_dir("ścieżka/do/folderu")`.

Jeden lint, który może zwracać dużo uwag i który stoi w sprzeczności z formatowaniem, jakie domyślnie tworzy RStudio, jest:

```
[trailing_whitespace_linter] Trailing whitespace is superfluous.
```

Te jedne uwagi możemy ignorować.

Okazjonalnie możemy też zignorować zbyt długie linie:

```
[line_length_linter] Lines should not be more than 80 characters.
```

ale zbyt wiele zbyt długich linii negatywnie odciska się na czytelności kodu, więc jedynie dobrze uzasadnione przypadki mają prawo być pozostawione.

Zdarza się też, że nazwy kolumn używane jak zmienne w tidyverse nie są wychwytywane przez linta, co powoduje dużą liczbę kolejnego typu uwag:

```
[object_usage_linter] no visible binding for global variable ‘NSE_accessed_column’
```

Da się to zaimplementować tak, aby nie triggerowało tego sprawdzenia... ale myślę, że ucierpiałaby na tym przejrzystość kodu, więc też można wtedy zignorować.

**Comment by kamilsi** [comment]
Closed with #42
