### ISSUE TITLE
Move study parameters to JSON payload body

### ISSUE THREAD

**Issue by lwalejko** [ttscience/unbiased#37]
Currently, `/study/minimisation_pocock` endpoint places all non-object parameters in query string in OpenAPI specification. Those parameters should all be placed in JSON body, so correct payload should look like this:

ENDPOINT: `/study/minimisation_pocock` (without query parameters)
POST BODY (`Content-Type: application/json`):

```json
{
  "identifier": "Test",
  "name": "Test name",
  "method": "var",
  "p": "0.85",
  "arms": {
    "placebo": 1,
    "active": 1
  },
  "covariates": {
    "sex": {
      "weight": 1,
      "levels": [
        "female",
        "male"
      ]
    },
    "weight": {
      "weight": 1,
      "levels": [
        "up to 60kg",
        "61-80 kg",
        "81 kg or more"
      ]
    }
  }
}
```

**Comment by kamilsi** [comment]
Closed in #40
