### ISSUE TITLE
"p" is being converted to numeric, which results with "NA" except of assertion

### ISSUE THREAD

**Issue by JagGlo** [ttscience/unbiased#41]
Przy testowaniu asercji na "p" nienumeryczne (np. "p": "a") okazało się, że linijka `p <- as.numeric(p)` skutkuje zamianą char na NA, a to nie wpada do błędów przy wywoływaniu testu: `err <- checkmate::check_numeric(p, lower = 0, upper = 1, len = 1)`

https://github.com/ttscience/unbiased/blame/8280039eb3190a0bdf50d3df1e5d07dce3c6b7f3/inst/plumber/unbiased_api/minimisation_pocock.R#L139

**Comment by kamilsi** [comment]
As part of #46 we moved place of "p" from path to body of request. It should be validated properly now. Closing.
