### ISSUE TITLE
GET /study

### ISSUE THREAD

**Issue by kamilsi** [ttscience/unbiased#50]
We need an endpoint that will return all existing studies within the DB with their IDs and definitions. The goal of this issue is to create

1. `GET /study` that returns a simplified list (IDs, names, codes)
2. `GET /study/{study_id}` that will return full information about the study

**Comment by salatak** [comment]
According to the previous arrangements, at this moment the study_id, study name and timestamp are listed for the `GET /study` endpoint. Additionally, I added the randomization method used because it seems important to me - researchers may not remember it.

**Comment by salatak** [comment]
Created pull request #62 with GET \study and GET \study\{study_id} endpoints and tests
