### ISSUE TITLE
Dobre praktyki kodu

### ISSUE THREAD

**Issue by ErdaradunGaztea** [ttscience/unbiased#6]
Należy uwzględnić kilka zasad, obecnych m.in. w tidyverse:

- [ ] Wydzielaj logiczne całości jako nazwane funkcje; dobrze nazwane funkcje i ich parametry sprawiają, że kod czyta się niemal jak prozę. Żadna ilość komentarzy nie da tego samego efektu. Nie mówiąc już o testowaniu, które jest tym łatwiejsze, im więcej funkcji przypada na dany zestaw operacji...
- [ ] Unikaj owijania zwracanej wartości w `return()`; jego użycie w R jest zarezerwowane do oznaczenia _early return_.
- [ ] Poświęć trochę czasu, by znaleźć idealne nazwy zmiennych - krótkie i treściwe.
  - [ ] Na marginesie, jeśli parametrem na wejściu jest `arms` w postaci wektora napisów, to nie powinno potem w kodzie być zastępowane przez liczbę ramion, a wektor przenoszony do `arm_names`.
- [ ] Nie używaj nieeksportowanych funkcji z innych pakietów (`:::`), patrz też #4.
- [ ] _Nigdy_ nie twórz ścieżek poprzez `paste(..., sep = "/")`. Wykorzystaj `file.path()` albo `fs::path()`.
- [ ] Nawet jeśli nie użyjesz struktury pakietu, to ładowanie paczek nigdy nie powinno odbywać się w środku kodu. Wszystkie `library()` powinny znajdować się na górze pliku.
- [ ] Większość pętli `for` i `while` da się zastąpić poprzez właściwie dobrane `lapply()` / `mapply()` albo `purrr::map()` / `purrr::pmap()`. Wielokrotne dołączanie rezultatu poprzez `c()`, `rbind()`, `cbind()`, etc. jest bardzo czasochłonne i kosztowne, szczególnie w porównaniu z mapowaniem.
- [ ] Nigdy nie zapisuj całej listy zmiennych poprzez `save()`, zamiast tego każdą zmienną zapisz osobnym `saveRDS()`; jest to bezpieczniejsze przy późniejszym ich wczytywaniu, jako że pierwszy sposób potencjalnie nadpisuje istniejące zmienne, podczas gdy w tym drugim to użytkownik wybiera nazwy nowych zmiennych.
- [ ] Pozwól użytkownikowi zapisywać wyniki pod dowolną ścieżką, a nie tylko w bieżącym katalogu. To, co robi sens w kontenerze dockerowym, jest bardzo złe w większości innych kontekstów, a to kwestia wprowadzenia dosłownie jednej zmiennej.

**Comment by kamilsi** [comment]
Thank you for highlighting these important practices. They are key to efficient and maintainable R programming and will be considered in our future development. We're closing this issue, but rest assured, your insights are valued and will guide our efforts to improve our codebase. These practices will also be valuable additions to our contributing guide once it's developed.
